// apps/shell/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommunicationService } from '@poc-aok-portalrahmen/angularLib';
import { addNumbers } from '@poc-aok-portalrahmen/jsLib';
import { UiComponent } from '@poc-aok-portalrahmen/ui';

@Component({
  standalone: true,
  imports: [RouterModule, UiComponent],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent implements OnInit {
  number = addNumbers(2, 1);
  message: string = '';
  constructor(private communicationService: CommunicationService) {}
  ngOnInit() {
    this.communicationService.message$.subscribe((message) => {
      this.message = message;
    });
  }

  // testing whether global eslint-rules are applied in Angular-Apps: hover :)
  functionWithoutReturnType() {
    return null;
  }
}

<div class="header container">
  <h2>Header area</h2>
  <h3>Toggle top Fachanwendung</h3>
  <ul class="remote-menu">
    <li><a routerLink="/remote1">Top: Remote 1</a></li>
    <li><a routerLink="/remote2">Top: Remote 2</a></li>
    <li><a routerLink="/remote4">Top: Remote 4</a></li>
  </ul>
  <h3>Toggle bottom Fachanwendung</h3>
  <ul class="remote-menu-bottom">
    <li><a [routerLink]="[{ outlets: { microfrontend2: ['remote1'] } }]">Bottom: Remote 1</a></li>
    <li><a [routerLink]="[{ outlets: { microfrontend2: ['remote2'] } }]">Bottom: Remote 2</a></li>
    <li><a [routerLink]="[{ outlets: { microfrontend2: ['remote4'] } }]">Bottom: Remote 4</a></li>
  </ul>
  <p class="js-lib">Function from shared JS library: {{ number }}</p>
  <lib-ui></lib-ui>
  <p>Message from Remote 1: {{ message }}</p>
</div>

<router-outlet></router-outlet>
<router-outlet name="microfrontend2"></router-outlet>

<div class="footer container">
  <h2>Footer area</h2>
</div>

// apps/remote3/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { addNumbers } from '@poc-aok-portalrahmen/jsLib';
import styles from './app.module.css';

export function App() {
  return (
    <div style={{ border: "2px solid darkblue", padding: "20px" }}>
      <p>Remote 3 Content</p>
      <p>Function from shared JS library: {addNumbers(5, 9)}</p>
    </div>
  );
}

// testing whether global eslint-rules are applied in React-Apps: hover :)
function functionWithoutReturnType() {
  return null;
}

export default App;
